//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSportEI20.WCFSeguridad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSeguridad.IModuloSeguridadService")]
    public interface IModuloSeguridadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSeguridadService/LoginUsuario", ReplyAction="http://tempuri.org/IModuloSeguridadService/LoginUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SportEl20.BE.ExceptionBase), Action="http://tempuri.org/IModuloSeguridadService/LoginUsuarioExceptionBaseFault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/SportEl20.BE")]
        SportEl20.BE.USUARIO LoginUsuario(SportEl20.BE.USUARIO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSeguridadService/LoginUsuario", ReplyAction="http://tempuri.org/IModuloSeguridadService/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.USUARIO> LoginUsuarioAsync(SportEl20.BE.USUARIO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSeguridadService/RecuperarContrasenia", ReplyAction="http://tempuri.org/IModuloSeguridadService/RecuperarContraseniaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SportEl20.BE.ExceptionBase), Action="http://tempuri.org/IModuloSeguridadService/RecuperarContraseniaExceptionBaseFault" +
            "", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/SportEl20.BE")]
        SportEl20.BE.USUARIO RecuperarContrasenia(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSeguridadService/RecuperarContrasenia", ReplyAction="http://tempuri.org/IModuloSeguridadService/RecuperarContraseniaResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.USUARIO> RecuperarContraseniaAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuloSeguridadServiceChannel : UnitTestSportEI20.WCFSeguridad.IModuloSeguridadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuloSeguridadServiceClient : System.ServiceModel.ClientBase<UnitTestSportEI20.WCFSeguridad.IModuloSeguridadService>, UnitTestSportEI20.WCFSeguridad.IModuloSeguridadService {
        
        public ModuloSeguridadServiceClient() {
        }
        
        public ModuloSeguridadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuloSeguridadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloSeguridadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloSeguridadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SportEl20.BE.USUARIO LoginUsuario(SportEl20.BE.USUARIO usuario) {
            return base.Channel.LoginUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.USUARIO> LoginUsuarioAsync(SportEl20.BE.USUARIO usuario) {
            return base.Channel.LoginUsuarioAsync(usuario);
        }
        
        public SportEl20.BE.USUARIO RecuperarContrasenia(string email) {
            return base.Channel.RecuperarContrasenia(email);
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.USUARIO> RecuperarContraseniaAsync(string email) {
            return base.Channel.RecuperarContraseniaAsync(email);
        }
    }
}
