//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSportEI20.xwcfDenuncia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="xwcfDenuncia.IDenunciasService")]
    public interface IDenunciasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/CrearDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/CrearDenunciaResponse")]
        SportEl20.BE.DENUNCIA CrearDenuncia(SportEl20.BE.DENUNCIA DenunciaCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/CrearDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/CrearDenunciaResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> CrearDenunciaAsync(SportEl20.BE.DENUNCIA DenunciaCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ObtenerDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ObtenerDenunciaResponse")]
        SportEl20.BE.DENUNCIA ObtenerDenuncia(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ObtenerDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ObtenerDenunciaResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> ObtenerDenunciaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ModificarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ModificarDenunciaResponse")]
        SportEl20.BE.DENUNCIA ModificarDenuncia(SportEl20.BE.DENUNCIA DenunciaModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ModificarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ModificarDenunciaResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> ModificarDenunciaAsync(SportEl20.BE.DENUNCIA DenunciaModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/EliminarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/EliminarDenunciaResponse")]
        void EliminarDenuncia(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/EliminarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/EliminarDenunciaResponse")]
        System.Threading.Tasks.Task EliminarDenunciaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ListarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ListarDenunciaResponse")]
        SportEl20.BE.DENUNCIA[] ListarDenuncia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDenunciasService/ListarDenuncia", ReplyAction="http://tempuri.org/IDenunciasService/ListarDenunciaResponse")]
        System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA[]> ListarDenunciaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDenunciasServiceChannel : UnitTestSportEI20.xwcfDenuncia.IDenunciasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DenunciasServiceClient : System.ServiceModel.ClientBase<UnitTestSportEI20.xwcfDenuncia.IDenunciasService>, UnitTestSportEI20.xwcfDenuncia.IDenunciasService {
        
        public DenunciasServiceClient() {
        }
        
        public DenunciasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DenunciasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DenunciasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DenunciasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SportEl20.BE.DENUNCIA CrearDenuncia(SportEl20.BE.DENUNCIA DenunciaCrear) {
            return base.Channel.CrearDenuncia(DenunciaCrear);
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> CrearDenunciaAsync(SportEl20.BE.DENUNCIA DenunciaCrear) {
            return base.Channel.CrearDenunciaAsync(DenunciaCrear);
        }
        
        public SportEl20.BE.DENUNCIA ObtenerDenuncia(string id) {
            return base.Channel.ObtenerDenuncia(id);
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> ObtenerDenunciaAsync(string id) {
            return base.Channel.ObtenerDenunciaAsync(id);
        }
        
        public SportEl20.BE.DENUNCIA ModificarDenuncia(SportEl20.BE.DENUNCIA DenunciaModificar) {
            return base.Channel.ModificarDenuncia(DenunciaModificar);
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA> ModificarDenunciaAsync(SportEl20.BE.DENUNCIA DenunciaModificar) {
            return base.Channel.ModificarDenunciaAsync(DenunciaModificar);
        }
        
        public void EliminarDenuncia(string id) {
            base.Channel.EliminarDenuncia(id);
        }
        
        public System.Threading.Tasks.Task EliminarDenunciaAsync(string id) {
            return base.Channel.EliminarDenunciaAsync(id);
        }
        
        public SportEl20.BE.DENUNCIA[] ListarDenuncia() {
            return base.Channel.ListarDenuncia();
        }
        
        public System.Threading.Tasks.Task<SportEl20.BE.DENUNCIA[]> ListarDenunciaAsync() {
            return base.Channel.ListarDenunciaAsync();
        }
    }
}
