CREATE DATABASE PROYECTODSD
go
USE PROYECTODSD
go

CREATE TABLE SEG_USUARIO(

ID_USUARIO INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(120) NOT NULL,
APE_PAT VARCHAR(150) NOT NULL,
APE_MAT VARCHAR(150) NOT NULL,
TIPOPROFESION VARCHAR(100) NOT NULL,
SEXO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
)

CREATE TABLE DENUNCIA(
ID_DENUNCIA INT PRIMARY KEY IDENTITY,
ID_USUARIO INT,
TIPODENUNCIA VARCHAR(100) NOT NULL,
FECHADENUNCIA DATE NOT NULL,
DESCRIPCION VARCHAR(255),
ESTADO VARCHAR(255) NOT NULL
CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO (ID_USUARIO),
)

CREATE TABLE DETALLE_FOTO(
ID_DETALLE_DENUNCIA INT IDENTITY,
ID_DENUNCIA INT,
FOTODENUNCIA VARCHAR(255) NOT NULL
--FOTODENUNCIA IMAGE NOT NULL
CONSTRAINT PK_DENUNCIAXUSUARIO PRIMARY KEY (ID_DETALLE_DENUNCIA,ID_DENUNCIA),
CONSTRAINT FK_DENUNCIA FOREIGN KEY (ID_DENUNCIA) REFERENCES DENUNCIA (ID_DENUNCIA)
)



ALTER TABLE [SEG_USUARIO] ADD COD_PERFIL CHAR(3) --ADM USU
GO

UPDATE [dbo].[SEG_USUARIO] SET COD_PERFIL='USU'


INSERT INTO [dbo].[SEG_USUARIO] VALUES ('ADMIN', 'ADMIN', 'ADMIN', 'ADMINISTRADOR', 'M', 'AdminDenuncia@outlook.com', 'dsd2016', 'ADM')

--PENDIENTE, PROCESO, ATENDIDO, CANCELADO
