CREATE DATABASE PROYECTODSD
go
USE PROYECTODSD
go

CREATE TABLE SEG_USUARIO(

ID_USUARIO INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(120) NOT NULL,
APE_PAT VARCHAR(150) NOT NULL,
APE_MAT VARCHAR(150) NOT NULL,
TIPOPROFESION VARCHAR(100) NOT NULL,
SEXO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
COD_PERFIL CHAR(3) NOT NULL, --ADM USU
)

CREATE TABLE DENUNCIA(
ID_DENUNCIA INT PRIMARY KEY IDENTITY,
ID_USUARIO INT,
TIPODENUNCIA VARCHAR(100) NOT NULL,
FECHADENUNCIA DATE NOT NULL,
DESCRIPCION VARCHAR(255),
ESTADO VARCHAR(255) NOT NULL --REGISTRADO, CONCLUIDA
CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO (ID_USUARIO),
)

CREATE TABLE DETALLE_FOTO(
ID_DETALLE_DENUNCIA INT IDENTITY,
ID_DENUNCIA INT,
FOTODENUNCIA VARCHAR(255) NOT NULL
--FOTODENUNCIA IMAGE NOT NULL
CONSTRAINT PK_DENUNCIAXUSUARIO PRIMARY KEY (ID_DETALLE_DENUNCIA,ID_DENUNCIA),
CONSTRAINT FK_DENUNCIA FOREIGN KEY (ID_DENUNCIA) REFERENCES DENUNCIA (ID_DENUNCIA)
)

go

INSERT INTO [dbo].[SEG_USUARIO] VALUES ('ADMIN', 'ADMIN', 'ADMIN', 'ADMINISTRADOR', 'M', 'Denuncia@gmail.com', 'dsd2016', 'ADM')

INSERT INTO [dbo].[SEG_USUARIO] VALUES ('Pedro', 'Lopez', 'Suarez', 'Vecino', 'M', 'pedro@gmail.com', '123456', 'USU')

INSERT INTO [dbo].[SEG_USUARIO] VALUES ('fernando', 'Sanchez', 'Angulo', 'Vecino', 'M', 'fernando@gmail.com', '123456', 'USU')
